# Generated by Django 4.1.3 on 2022-11-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ibsn',
            new_name='isbn',
        ),
    ]
